apiVersion: v1
kind: Namespace
metadata:
  name: demo-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ui
  namespace: demo-ui
  labels:
    app: demo-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-ui
  template:
    metadata:
      labels:
        app: demo-ui
    spec:
      containers:
        - name: demo-ui
          image: '192.168.87.129/demo/demo-ui:0.0.1'
          imagePullPolicy: Always
          ports:
            - containerPort: 8677
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-ui
  namespace: demo-ui
spec:
  ports:
    - port: 8677
      targetPort: 8677
  selector:
    app: demo-ui
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: demo-ui-nodeport
  namespace: demo-ui
spec:
  type: NodePort
  selector:
    app: demo-ui
  ports:
    - name: http
      port: 80
      targetPort: 8677
      nodePort: 30880